---
namespace: linsomniac
name: fsbuilder
version: 0.2.0
readme: README.md
authors:
  - Sean
description: >-
  Ansible module that consolidates multiple filesystem operations
  (template, copy, mkdir, touch, rm, symlink, hardlink, lineinfile,
  blockinfile) into a single task.
license:
  - CC0-1.0
tags:
  - filesystem
  - template
  - copy
  - file
  - lineinfile
  - blockinfile
# AIDEV-NOTE: No collection dependencies needed. ansible.builtin is part of
# ansible-core itself and must not be listed here (Galaxy can't resolve it).
# The minimum ansible-core version requirement is documented in README.md.
dependencies: {}
repository: https://github.com/linsomniac/fsbuilder
# AIDEV-NOTE: build_ignore uses fnmatch (not gitignore). No ** recursive globs,
# no trailing slashes. .git and <ns>-<name>-*.tar.gz are excluded by default.
# Cache dirs need both root and '*/' prefix patterns due to fnmatch limitation.
build_ignore:
  # Build artifacts
  - '*.tar.gz'
  # Version control and CI
  - .github
  - .gitignore
  # Python caches (root + subdirectory level due to fnmatch limitation)
  - .mypy_cache
  - '*/.mypy_cache'
  - __pycache__
  - '*/__pycache__'
  - .pytest_cache
  - '*/.pytest_cache'
  - .ruff_cache
  # Test infrastructure (CRITICAL - test-collections has recursive symlink loop)
  - test-collections
  - tests
  - molecule
  # Development environment
  - .venv
  - .vscode
  - .idea
  - pyproject.toml
  - uv.lock
  - Makefile
  - conftest.py
  - .coverage
  # Internal documentation
  - design.md
  - fsbuilder.md
  # AI/tool config
  - .claude
  - .codex
