---
# AIDEV-NOTE: This converge uses tasks that are self-contained and idempotent.
# Excluded: touch (always reports changed), state=absent (needs prior create),
# lineinfile/blockinfile (need base file creation which fights with modify step).
- name: Converge - idempotency test
  hosts: all
  gather_facts: false
  vars:
    test_dir: /tmp/fsb_test
    greeting: "Hello from fsbuilder"
  tasks:
    - name: Create test directory
      linsomniac.fsbuilder.fsbuilder:
        dest: "{{ test_dir }}/app"
        state: directory
        mode: "0755"

    - name: Copy with inline content
      linsomniac.fsbuilder.fsbuilder:
        dest: "{{ test_dir }}/app/content.txt"
        state: copy
        content: "known content string\n"

    - name: Template with inline content
      linsomniac.fsbuilder.fsbuilder:
        dest: "{{ test_dir }}/app/inline_template.txt"
        state: template
        content: "Rendered: {{ greeting }}\n"

    - name: Create symlink
      linsomniac.fsbuilder.fsbuilder:
        dest: "{{ test_dir }}/app/link_to_content"
        state: link
        src: "{{ test_dir }}/app/content.txt"

    - name: Create hard link
      linsomniac.fsbuilder.fsbuilder:
        dest: "{{ test_dir }}/app/hard_to_content"
        state: hard
        src: "{{ test_dir }}/app/content.txt"

    - name: Ensure file exists
      linsomniac.fsbuilder.fsbuilder:
        dest: "{{ test_dir }}/app/ensured.txt"
        state: exists
