---
# AIDEV-NOTE: Idempotency scenario runs converge twice and checks no changes
# on second run (excludes touch which always reports changed).
driver:
  name: docker
platforms:
  - name: fsbuilder-idempotency
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: false
    tmpfs:
      - /tmp
provisioner:
  name: ansible
  config_options:
    defaults:
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/test-collections:~/.ansible/collections
  playbooks:
    prepare: ../default/prepare.yml
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
